#!/bin/sh
echo Starting Webmin server in /usr/local/webmin
trap '' 1
LANG=
export LANG
#PERLIO=:raw
unset PERLIO
export PERLIO
PERLLIB=/usr/local/webmin
export PERLLIB
exec '/usr/local/webmin/miniserv.pl' $* /etc/webmin/miniserv.conf
